### ISSUE TITLE
Discord bot closed while processing long request

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#103]
**Describe the bug**
When processing long request such as crawling really long toc that have pagination such as comrademao, lnmtl bot suddenly closed and generate error as below

```
Exception ignored in: <coroutine object DiscordBot.on_message at 0x7faf61255410>
Traceback (most recent call last):
  File "./lncrawl/bots/discord.py", line 44, in on_message
    await self.handle_message(message)
  File "./lncrawl/bots/discord.py", line 64, in handle_message
    await handler.process(message)
  File "./lncrawl/bots/discord.py", line 118, in process
    await self.state()
  File "./lncrawl/bots/discord.py", line 147, in handle_novel_url
    await self.get_novel_info()
  File "./lncrawl/bots/discord.py", line 290, in get_novel_info
    len(self.app.crawler.chapters)
  File "./lncrawl/bots/discord.py", line 99, in send
    await self.client.send_typing(self.user)
  File "/home/yudi/.local/lib/python3.6/site-packages/discord/client.py", line 1174, in send_typing
    yield from self.http.send_typing(channel_id)
  File "/home/yudi/.local/lib/python3.6/site-packages/discord/http.py", line 203, in request
    yield from r.release()
  File "/home/yudi/.local/lib/python3.6/site-packages/discord/http.py", line 82, in __exit__
    self.lock.release()
  File "/usr/lib/python3.6/asyncio/locks.py", line 205, in release
    self._wake_up_first()
  File "/usr/lib/python3.6/asyncio/locks.py", line 220, in _wake_up_first
    fut.set_result(True)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 580, in call_soon
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-03-11 13:17:00,137 [ERROR] (asyncio)
Task was destroyed but it is pending!
```
Sometimes even happened on wuxiaworld.com crawler but i cannot reproduce it, seems intermittent

**Let us know**
- Novel URL: [https://comrademao.com/novel/within-three-inches/]
- App Version: [e.g. 2.8.3]
- Package: [github]
- OS: [ubuntu 18.10]

**Comment by dipu-bd** [comment]
Looks like it is related to this one: https://stackoverflow.com/a/32611438/1583052 

If nothing is sent around 4 seconds, the event loop closes automatically. I do not know how to solve this yet. For now, I have added a try-catch to the `handle_message` method.

**Comment by dipu-bd** [comment]
Superseded by #140
