### ISSUE TITLE
Error with json.decoder when the App is called

### ISSUE THREAD

**Issue by RomuloPS** [dipu-bd/lightnovel-crawler#1066]
## Describe the bug
Bug occurs when the app is called, no need for input.

```
================================================================================
╭╮╱╱╱╱╱╱╭╮╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╱╱╱╱╱╱╱╭╮
┃┃╱╱╱╱╱╱┃┃╭╯╰╮╱╱╱╱╱╱╱╱╱╱╱┃┃╱┃╭━╮┃╱╱╱╱╱╱╱╱╱┃┃
┃┃╱╱╭┳━━┫╰┻╮╭╋━╮╭━━┳╮╭┳━━┫┃╱┃┃╱╰╋━┳━━┳╮╭╮╭┫┃╭━━┳━╮
┃┃╱╭╋┫╭╮┃╭╮┃┃┃╭╮┫╭╮┃╰╯┃┃━┫┃╱┃┃╱╭┫╭┫╭╮┃╰╯╰╯┃┃┃┃━┫╭╯
┃╰━╯┃┃╰╯┃┃┃┃╰┫┃┃┃╰╯┣╮╭┫┃━┫╰╮┃╰━╯┃┃┃╭╮┣╮╭╮╭┫╰┫┃━┫┃
╰━━━┻┻━╮┣╯╰┻━┻╯╰┻━━╯╰╯╰━━┻━╯╰━━━┻╯╰╯╰╯╰╯╰╯╰━┻━━┻╯
╱╱╱╱╱╭━╯┃ v2.28.3
╱╱╱╱╱╰━━╯ 🔗 https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rum/.local/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/home/rum/.local/lib/python3.9/site-packages/lncrawl/__init__.py", line 14, in main
    start_app()
  File "/home/rum/.local/lib/python3.9/site-packages/lncrawl/core/__init__.py", line 69, in start_app
    load_sources()
  File "/home/rum/.local/lib/python3.9/site-packages/lncrawl/core/sources.py", line 316, in load_sources
    __check_updates()
  File "/home/rum/.local/lib/python3.9/site-packages/lncrawl/core/sources.py", line 143, in __check_updates
    __load_current_index_data()
  File "/home/rum/.local/lib/python3.9/site-packages/lncrawl/core/sources.py", line 103, in __load_current_index_data
    __current_index_data = json.load(fp)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 113299 (char 113298)
```

## Let us know

**Input**: none
**App type**: PIP and Linux binary
**App version**: 2.28.3 and 2.28.2
**Your OS**: Linux

**Comment by dipu-bd** [comment]
delete `~/.lncrawl/` folder and try again. I will handle this error in the next version
