### ISSUE TITLE
the discord bot does not start

### ISSUE THREAD

**Issue by loro102** [dipu-bd/lightnovel-crawler#119]
You have followed the instructions to start the discord bot and get some errors that seem to fail when creating the asyncio.async task
 
 python . --bot discord
================================================================================
                             Lightnovel Crawler #2.9.4
            Download lightnovels into html, text, epub, mobi and json
--------------------------------------------------------------------------------
                          << LOG LEVEL: INFO
--------------------------------------------------------------------------------
 $ VERSION 2.9.3 IS NOW AVAILABLE!
 -> To upgrade: pip install -U lightnovel-crawler
 -> To download: https://goo.gl/sc4EZh
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\__main__.py", line 4, in <module>
    main()
  File ".\lncrawl\__init__.py", line 13, in main
    start_app()
  File ".\lncrawl\core\__init__.py", line 95, in start_app
    raise err
  File ".\lncrawl\core\__init__.py", line 92, in start_app
    run_bot(bot)
  File ".\lncrawl\bots\__init__.py", line 23, in run_bot
    from ..bots.discord import DiscordBot
  File ".\lncrawl\bots\discord.py", line 10, in <module>
    import discord
  File "C:\Users\usuario\AppData\Roaming\Python\Python37\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\usuario\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\usuario\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\usuario\AppData\Roaming\Python\Python37\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by dipu-bd** [comment]
It is only for the purpose of running your own bot using this app.

First, you have to provide your discord bot token to start it. You can pass the token like this-
```
python . --bot discord '{ "DISCORD_TOKEN": "<PUT YOUR TOKEN HERE>" }'
```

But it is recommended to create a `.env` file copying the `.env.example` file and put your token there.

Here is how to get a token:
https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
