### ISSUE TITLE
lightnovelstranslations.com: failing to download the cover and create the epub

### ISSUE THREAD

**Issue by satozuki** [dipu-bd/lightnovel-crawler#1237]
## Let us know

**Novel URL**:     https://lightnovelstranslations.com/isekai-meikyuu-de-dorei-harem-wo/
**App Location**:    PIP
**App Version**:   v2.28.11
**Your OS**:   Linux

## Describe this issue

Failing to download the cover image and failing to generate the epub

```
:~$  lncrawl -s https://lightnovelstranslations.com/isekai-meikyuu-de-dorei-harem-wo/
================================================================================
╭╮╱╱╱╱╱╱╭╮╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╱╱╱╱╱╱╱╭╮
┃┃╱╱╱╱╱╱┃┃╭╯╰╮╱╱╱╱╱╱╱╱╱╱╱┃┃╱┃╭━╮┃╱╱╱╱╱╱╱╱╱┃┃
┃┃╱╱╭┳━━┫╰┻╮╭╋━╮╭━━┳╮╭┳━━┫┃╱┃┃╱╰╋━┳━━┳╮╭╮╭┫┃╭━━┳━╮
┃┃╱╭╋┫╭╮┃╭╮┃┃┃╭╮┫╭╮┃╰╯┃┃━┫┃╱┃┃╱╭┫╭┫╭╮┃╰╯╰╯┃┃┃┃━┫╭╯
┃╰━╯┃┃╰╯┃┃┃┃╰┫┃┃┃╰╯┣╮╭┫┃━┫╰╮┃╰━╯┃┃┃╭╮┣╮╭╮╭┫╰┫┃━┫┃
╰━━━┻┻━╮┣╯╰┻━┻╯╰┻━━╯╰╯╰━━┻━╯╰━━━┻╯╰╯╰╯╰╯╰╯╰━┻━━┻╯
╱╱╱╱╱╭━╯┃ v2.28.11
╱╱╱╱╱╰━━╯ 🔗 https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

➡ Press  Ctrl + C  to exit

Retrieving novel info...
https://lightnovelstranslations.com/isekai-meikyuu-de-dorei-harem-wo/
NOVEL: A Harem in the Fantasy World Dungeon
11 volumes and 256 chapters found
? Enter output directory: /home/alien/Downloads/ln/Lightnovels/lightnovelstranslations-com/A Harem in the Fantasy World Dungeon
? Which chapters to download? Everything! (256 chapters)
? 256 chapters selected Continue
? Which output formats to create? done (2 selections)
? How many files to generate? Split by volume into multiple files
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:53<00:00,  4.76ch/s]
Processed 256 chapters
Failed to download original cover image: None -> /home/alien/Downloads/ln/Lightnovels/lightnovelstranslations-com/A Harem in the Fantasy World Dungeon/cover.jpg ()

--------------------------------------------------------------------------------
 🔗  https://github.com/dipu-bd/lightnovel-crawler/issues 
================================================================================

```

### Additional information

I have tried different options, but all of them failing:

- I have manually added a cover in the folder 
- I have tried to generate only epub or only mobi 
- I have tried both multiple volumes or only one

### Personal feedback

Thank you for all your effort, I really appreciate it.

I have been using lightnovel-crawler for a while and I love it.

**Comment by dipu-bd** [comment]
Failing to download the cover has nothing to do with failing to generate epub. I am not sure where the problem is from your console log. Please run using `-lll` and send the log here:

```
$ lncrawl -lll -s https://lightnovelstranslations.com/isekai-meikyuu-de-dorei-harem-wo/
```

**Comment by satozuki** [comment]
hi @dipu-bd 

Thanks for your fast answer, following the full log:

[ln.log](https://github.com/dipu-bd/lightnovel-crawler/files/7844843/ln.log)

**Comment by dipu-bd** [comment]
Is it the full log? The program seemed to stopped in the middle. The log file should end with this footer:

```
--------------------------------------------------------------------------------
 🔗  https://github.com/dipu-bd/lightnovel-crawler/issues 
================================================================================
```

**Comment by satozuki** [comment]
Something interesting:

**V2:**

I started with a new folder and got the exact log shared previously, repeated with the same command on the same folder and received the following error:

```
Traceback (most recent call last):
  File "/home/TheUser/.local/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/__init__.py", line 14, in main
    start_app()
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/core/__init__.py", line 79, in start_app
    raise err
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/core/__init__.py", line 76, in start_app
    run_bot(bot)
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/bots/__init__.py", line 17, in run_bot
    ConsoleBot().start()
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/bots/console/start.py", line 79, in start
    self.app.start_download()
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/core/app.py", line 172, in start_download
    download_chapter_images(self)
  File "/home/TheUser/.local/lib/python3.8/site-packages/lncrawl/core/downloader.py", line 220, in download_chapter_images
    full_url = app.crawler.absolute_url(img['src'], page_url=chapter['url'])
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 1321, in __getitem__
    return self.attrs[key]
KeyError: 'src'
```
but in neither of them I was able to reach:

```
--------------------------------------------------------------------------------
 🔗  https://github.com/dipu-bd/lightnovel-crawler/issues 
================================================================================
```

Full log here:
[ln_v2_new-lll_repeated-lll.log](https://github.com/dipu-bd/lightnovel-crawler/files/7846523/ln_v2_new-lll_repeated-lll.log)

**V3:**

Then decided to repeat the command without log level and then with log level "warn".

Without -l I get the message displayed, but with -l I get the previously mentioned error.

Full log here:
[ln_v3_no-l_and-l.log](https://github.com/dipu-bd/lightnovel-crawler/files/7846533/ln_v3_no-l_and-l.log)

**Comment by dipu-bd** [comment]
Thanks. I think I got where the problem is. I shall publish a new version fixing it soon.

**Comment by dipu-bd** [comment]
Any update on this? Have you checked the latest version?

**Comment by satozuki** [comment]
Hi @dipu-bd 
I must apologise it has been couple of difficult weeks and did not notice your answer.

I am getting a different error now, but only if I use -ll. When I have -lll or without logs I am not getting any errors.

Without logs no error appears:
[Fantasy-nol.txt](https://github.com/dipu-bd/lightnovel-crawler/files/8055988/Fantasy-nol.txt)

Using -ll I am getting
```
Traceback (most recent call last):
  File "/home/user/.local/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/__init__.py", line 14, in main
    start_app()
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/core/__init__.py", line 80, in start_app
    raise err
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/core/__init__.py", line 77, in start_app
    run_bot(bot)
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/bots/__init__.py", line 17, in run_bot
    ConsoleBot().start()
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/bots/console/integration.py", line 100, in start
    self.app.start_download()
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/core/app.py", line 174, in start_download
    download_chapter_images(self)
  File "/home/user/.local/lib/python3.8/site-packages/lncrawl/core/downloader.py", line 229, in download_chapter_images
    full_url = app.crawler.absolute_url(img['src'], page_url=chapter['url'])
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 1321, in __getitem__
    return self.attrs[key]
KeyError: 'src'
```
Full log can be found here:
[Fantasy-ll.txt](https://github.com/dipu-bd/lightnovel-crawler/files/8055989/Fantasy-ll.txt)

When I use -lll there is no error:
[Fantasy-lll.txt](https://github.com/dipu-bd/lightnovel-crawler/files/8055992/Fantasy-lll.txt)

Thank you again and I apologise for the delay.

Regards

**Comment by dipu-bd** [comment]
Found the cause of the issue and fixed it. It should work in version 2.29.7

**Comment by satozuki** [comment]
YES!
It works!

Thank you @dipu-bd !

I really appreciate it.
