### ISSUE TITLE
Error while using babelnovel crawler

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#148]
**Describe the bug**
After entering Babel novel book url getting error :
```
/storage/emulated/0 $ mkdir Novel2
/storage/emulated/0 $ cd Novel2                             
/storage/emulated/0/Novel2 $ lncrawl                        
============================================================                 
ledger Lightnovel Crawler four_leaf_clover2.9.12                       
https://github.com/dipu-bd/lightnovel-crawler       
------------------------------------------------------------⮕ 

Press  Ctrl + C  to exit                                  

? Enter novel page url or query novel:  https://babelnovel.com/books/poison-genius-consort                              
Retrieving novel info...                                     

exclamation Error: Expecting value: line 1 column 1 (char 0)        

------------------------------------------------------------ 
link  https://github.com/dipu-bd/lightnovel-crawler/issues     
pray  https://saythanks.io/to/dipu-bd                         
============================================================
/storage/emulated/0/Novel2 $
```

**Let us know**
- Novel URL: [https://babelnovel.com/books/poison-genius-consort]
- App Version: [e.g. 2.9.12]
- Package: [pip]
- OS: [android using pydroid3 and Ubuntu 19.04]

**Comment by dipu-bd** [comment]
```
/storage/emulated/0 $ lncrawl -s https://babelnovel.com/books/poison-genius-consort -lll                                                                  =============================================================================                         📒 Lightnovel Crawler 🍀2.9.12                                         https://github.com/dipu-bd/lightnovel-crawler               -----------------------------------------------------------------------------                         🔊 LOG LEVEL: DEBUG                                  -----------------------------------------------------------------------------2019-06-15 17:04:30,104 [DEBUG] (urllib3.connectionpool)                     Starting new HTTPS connection (1): pypi.org:443                              2019-06-15 17:04:31,429 [DEBUG] (urllib3.connectionpool)                     https://pypi.org:443 "GET /pypi/lightnovel-crawler/json HTTP/1.1" 200 11284  ⮕ Press  Ctrl + C  to exit                                                   2019-06-15 17:04:31,649 [INFO] (APP)                                         Initialized App                                                              2019-06-15 17:04:31,649 [INFO] (APP)                                         Detected URL input
2019-06-15 17:04:31,649 [INFO] (APP)
Initializing crawler for: https://babelnovel.com/
Retrieving novel info...
2019-06-15 17:04:31,650 [INFO] (BABELNOVEL)
Canonical name: poison-genius-consort
2019-06-15 17:04:31,651 [DEBUG] (BABELNOVEL)
Visiting https://babelnovel.com/api/books/poison-genius-consort
2019-06-15 17:04:31,655 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): babelnovel.com:443
2019-06-15 17:04:33,265 [DEBUG] (urllib3.connectionpool)
https://babelnovel.com:443 "GET /api/books/poison-genius-consort HTTP/1.1" 302 19
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/lncrawl", line 10, in <module>
    sys.exit(main())
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/__init__.py", line 13, in main
    start_app()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/core/__init__.py", line 97, in start_app
    raise err
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/core/__init__.py", line 94, in start_app
    run_bot(bot)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/bots/__init__.py", line 18, in run_bot
    ConsoleBot().start()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/bots/console.py", line 46, in start
    self.app.get_novel_info()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/core/app.py", line 127, in get_novel_info
    self.crawler.read_novel_info()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/spiders/babelnovel.py", line 50, in read_novel_info
    data = self.get_json(self.novel_url)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/lncrawl/utils/crawler.py", line 185, in get_json
    return response.json()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/storage/emulated/0 $
```

**Comment by dipu-bd** [comment]
it was a cookie/session data related problem. i fixed it. it will be available from the next version.
