### ISSUE TITLE
wuxiaworld.site

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1586]
**Novel URL**:     https://wuxiaworld.site/novel/coming-of-the-villain-boss-wuxia-world-novels/
**App Location**:    PIP
**App Version**:   2.35.0

So I was going to edit this source and add the following url as it same site. https://wuxiaworldsite.com but I noticed the source didn't work. I've tried multiple different ways of fixing it myself but keep getting same error.

```
? Enter novel page url or query novel: https://wuxiaworld.site/novel/coming-of-the-villain-boss-wuxia-world-novels/
Retrieving novel info...
https://wuxiaworld.site/novel/coming-of-the-villain-boss-wuxia-world-novels/
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\sources\en\w\wuxiasite.py", line 37, in read_novel_info
    soup = self.get_soup(self.novel_url)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\crawler.py", line 313, in get_soup
    response = self.get_response(url, **kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\crawler.py", line 278, in get_response
    result = self.__process_request('get', url, **kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\crawler.py", line 144, in __process_request
    raise e
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\crawler.py", line 135, in __process_request
    response.raise_for_status()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://wuxiaworld.site/novel/coming-of-the-villain-boss-wuxia-world-novels/
NOVEL:
0 volumes and 0 chapters found

 ! Error: No chapters found 
<class 'Exception'>
File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 98, in start
    raise e
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 90, in start
    _download_novel()
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 79, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\app.py", line 155, in get_novel_info
    raise Exception('No chapters found')
```

**Comment by budikesuma** [comment]
@SirGryphin 

Based on my knowledge, `wuxiaworld.site` has switched to a new domain name called `daonovel.com`, if you don't believe me, you can try using your novel link above, and then directly change the name of `wuxiaworld.site` to its new domain: `daonovel.com`. You will find the exact same novel.

**Comment by SirGryphin** [comment]
@budikesuma I've been using daonovel for other novels, I will have to try daonovel source and change it for wuxiaworld domains see if that fixes it. I'm sure I tried and got same error earlier so it might be something on their end, I will use daonovel for now.

**Comment by idMysteries** [comment]
@SirGryphin if you haven't noticed, the 403 error has recently been related to cloudflare.

**Comment by budikesuma** [comment]
No, it has been put on the rejected sources list.
.
.
![Screenshot_20220918-222150_Browser](https://user-images.githubusercontent.com/50254552/190914824-2719adb8-dc78-43a5-8d29-ea6d52054661.jpg)

**Comment by SirGryphin** [comment]
@budikesuma thanks for the info didn't notice.
