### ISSUE TITLE
Babelnovel

### ISSUE THREAD

**Issue by kajack** [dipu-bd/lightnovel-crawler#170]
Getting https://babelnovel.com/books/magic-love-ring results in around 800 or 900 chapters with KBody is empty.

From chapter 1,200 to the end is good.

I tried other novels there and doesn't give that result.

**Comment by dipu-bd** [comment]
babelnovel crawler has some issue. i will fix them next time i start working on it

**Comment by kajack** [comment]
I used the log function and it seems the error to be this one:

`Traceback (most recent call last):
  File "c:\users\victor.abrate\appdata\local\programs\python\python37-32\lib\site-packages\src\core\downloader.py", line 86, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\users\victor.abrate\appdata\local\programs\python\python37-32\lib\site-packages\src\spiders\babelnovel.py", line 128, in download_chapter_body
    tag.name = 'p'
  File "c:\users\victor.abrate\appdata\local\programs\python\python37-32\lib\site-packages\bs4\element.py", line 754, in name
    raise AttributeError("A NavigableString cannot be given a name.")
AttributeError: A NavigableString cannot be given a name.`

**Comment by dipu-bd** [comment]
I see the problem. Thanks. I will push a fix tomorrow night.

**Comment by dipu-bd** [comment]
fixed in version 2.11.1
