### ISSUE TITLE
some scribblehub links that are not working

### ISSUE THREAD

**Issue by slanesteve** [dipu-bd/lightnovel-crawler#1709]
## Let us know

**Novel URL**:     <your novel url or query> 
**App Location**:    PIP | EXE | Discord | Telegram 
**App Version**:   x.y.z

**Comment by slanesteve** [comment]
https://www.scribblehub.com/series/258548/reincarnated-as-a-completely-average-person/

https://www.scribblehub.com/series/252562/a-sinners-chance/

errors when trying: (errors same for any attempt on scribblehub)

Exception in thread Thread-2 (read_novel_info):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\steve\.lncrawl\sources\en\s\scribblehub.py", line 97, in read_novel_info
    response = self.submit_form(
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\core\scraper.py", line 223, in submit_form
    return self.post_response(url, data=data, headers=headers, **kwargs)
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\core\scraper.py", line 204, in post_response
    return self.__process_request(
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\core\scraper.py", line 106, in __process_request
    raise e
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\core\scraper.py", line 101, in __process_request
    response.raise_for_status()
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.scribblehub.com/wp-admin/admin-ajax.php

 ! Error: No chapters found
<class 'Exception'>
File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\bots\console\integration.py", line 88, in start
    raise e
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\bots\console\integration.py", line 82, in start
    _download_novel()
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\bots\console\integration.py", line 72, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lncrawl\core\app.py", line 121, in get_novel_info
    raise Exception("No chapters found")

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/issues/1707
@dipu-bd
