### ISSUE TITLE
lightnovelpub.com

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1720]
**Novel URL**:     https://www.lightnovelpub.com/novel/emperors-domination-novel-17092239
**App Location**:    PIP
**App Version**:   3.0.1

Fails to find chapters page, it's a different page each time I try. First try it was page 19 then 23 and now 24.

This is the error:
``` python
Retrieving novel info...
https://www.lightnovelpub.com/novel/emperors-domination-novel-17092239
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\.lncrawl\sources\en\l\lightnovelpub.py", line 98, in read_novel_info
    page_soups = [soup] + [f.result() for f in futures]
  File "C:\Users\User\.lncrawl\sources\en\l\lightnovelpub.py", line 98, in <listcomp>
    page_soups = [soup] + [f.result() for f in futures]
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\core\scraper.py", line 289, in get_soup
    response = self.get_response(url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\core\scraper.py", line 194, in get_response
    return self.__process_request(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\core\scraper.py", line 106, in __process_request
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\core\scraper.py", line 101, in __process_request
    response.raise_for_status()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.lightnovelpub.com/novel/emperors-domination-novel-17092239/chapters/page-24

 ! Error: No chapters found
<class 'Exception'>
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\bots\console\integration.py", line 88, in start
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\bots\console\integration.py", line 82, in start
    _download_novel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\bots\console\integration.py", line 72, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\lncrawl\core\app.py", line 121, in get_novel_info
    raise Exception("No chapters found")
```

**Comment by ShakeBake** [comment]
I belive you can re-download chapter that failed to be found. Just run the script again and re-write over the file when it asks to download missing chapters. Get a fresh IP if you've been continuously trying/still get blocked, that helped for me.

**Comment by idMysteries** [comment]
@dipu-bd cloudflare
