### ISSUE TITLE
myboxnovel

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1766]
Does not get chapters, also comes up with 503 error and when I open link I get this page.

![Screenshot 2022-11-06 164139](https://user-images.githubusercontent.com/36343615/200183211-ba302063-eb12-4935-b242-7fae187b4c02.png)

**Novel URL**:    https://myboxnovel.com/book/reincarnation-i-have-always-been-rich/
**App Location**:    PIP
**App Version**:  3.0.1

```python
? Enter novel page url or query novel: https://myboxnovel.com/book/reincarnation-i-have-always-been-rich/
Retrieving novel info...
https://myboxnovel.com/book/reincarnation-i-have-always-been-rich/
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\templates\soup\general.py", line 16, in read_novel_info
    soup = self.get_soup(self.novel_url)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 289, in get_soup
    response = self.get_response(url, **kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 194, in get_response
    return self.__process_request(
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 106, in __process_request
    raise e
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 101, in __process_request
    response.raise_for_status()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://myboxnovel.com/book/reincarnation-i-have-always-been-rich/

 ! Error: No chapters found 
<class 'Exception'>
File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 88, in start
    raise e
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 82, in start
    _download_novel()
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\bots\console\integration.py", line 72, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\app.py", line 121, in get_novel_info
    raise Exception("No chapters found")
```

**Comment by jere344** [comment]
#1758

**Comment by SirGryphin** [comment]
@jere344 so the mandra template that myboxnovel uses needs updating then, not sure how that will affect other sites/sources using it unless there all getting this error anyway.

**Comment by jere344** [comment]
It seems that you have another problem, perhaps they saw too much requests from you and manually blocked you ?

If someone not blocked want to use this source he can temporarily use `requests.post`, but it is a workaround for the bug #1758.

![image](https://user-images.githubusercontent.com/86294972/200318911-e56e7701-c3ba-4380-9259-7af6be75a766.png)

And when using `requests.post` in madaratemplate it works fine for me
![image](https://user-images.githubusercontent.com/86294972/200319122-1a9bb81e-f28e-4c8d-b714-dfa27eb809ff.png)

**Comment by SirGryphin** [comment]
@jere344 Thanks for this workaround.

@dipu-bd is it worth adding to mandra template? or will `submit_form` be fix?  Just want to know if it worth making a Pull Request.

**Comment by jere344** [comment]
I hope `submit_for` will be fix, perhaps I will look into it but doubt I can fix the issue cleanly.
I don't think we should add it to the mandra template as it would be inconsistant with current code.
And if I understand well, `submit_form` is supposed to work better if the website has any crawling protection, so fixing it will make the source more reliable than just using  `requests.post` that will break if the source get cloudflare or something like that.
(And we still need @dipu-bd opinion)

**Comment by zerty** [comment]
the default rate that is detected is 160 request per seconds, i had the problem in #1772 that i fixed with a sleep. It might also be a problem with the user agent

**Comment by dipu-bd** [comment]
> fixing it will make the source more reliable than just using `requests.post`

I agree. 

`submit_form`  adds some extra headers. Maybe you can try overriding these headers, and it may work.

**Comment by dipu-bd** [comment]
fixed
