### ISSUE TITLE
[windows] Failed to generate cover image

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#181]
**Describe the bug**
```
Failed to generate cover image
Traceback (most recent call last):
  File "src\core\downloader.py", line 47, in downlod_cover
  File "src\utils\racovimge.py", line 136, in generate_image
NameError: name 'svg2png' is not defined
No cover image
```

**Let us know**
- Novel URL: https://www.rebirth.online/novel/artunis
- App Version: 2.13.6
- Package: EXE
- OS: Windows 10

**Comment by dipu-bd** [comment]
Some of the resource files used in `CairoSVG` are not being properly binded with PyInstaller. Maybe manually adding resources files to the bundle would work?

**Comment by dipu-bd** [comment]
solved! added all data files of cairosvg and its dependencies with pyinstaller. now it should work on standalone packages.

- [x] Linux -- okay
- [ ] Windows -- pending test

**Comment by dipu-bd** [comment]
Another issue, with template generator jinja2:
```
Failed to generate cover image
Traceback (most recent call last):
  File "/home/dipu/.local/lib/python3.6/site-packages/lncrawl/core/downloader.py", line 46, in downlod_cover
    author=app.crawler.novel_author or '',
  File "/home/dipu/.local/lib/python3.6/site-packages/lncrawl/utils/racovimge.py", line 125, in generate_image
    svg = random(title, author)
  File "/home/dipu/.local/lib/python3.6/site-packages/lncrawl/utils/racovimge.py", line 119, in random
    return env.get_template(template + '.svg').render(**kargs)
  File "/home/dipu/.local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/dipu/.local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/dipu/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/dipu/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Window.svg

```
