### ISSUE TITLE
it shows me this when I do it with webnovel

### ISSUE THREAD

**Issue by KuraisoraHoshi26311002** [dipu-bd/lightnovel-crawler#1815]
it shows me this when I do it with webnovel
![Uploading 206707423-c52bef85-20a6-4851-a6a5-177cdd1012c1.jpg…]()

**Comment by dipu-bd** [comment]
The image was not uploaded properly. Also give an example novel link

**Comment by dipu-bd** [comment]
possibly a duplicate of #1810

**Comment by DomID00** [comment]
https://www.webnovel.com/book/conquering-second-dimension-begins-from-doupo_23992671305061905

I copy paste what it shows me

===================================
-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.webnovel.com/book/conquering-second-dimension-begins-from-doupo_2399
2671305061905
Retrieving novel info...
https://www.webnovel.com/book/conquering-second-dimension-begins-from-doupo_23992671305061905
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 88, in read_novel_info
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 69, in read_novel_info_in_scraper
    self.get_csrf()
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 36, in get_csrf
    self.csrf = self.cookies["_csrfToken"]
KeyError: '_csrfToken'

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 88, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 82, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 72, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 122, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...
====================================
