### ISSUE TITLE
Fix this source "Webnovel"

### ISSUE THREAD

**Issue by DomID00** [dipu-bd/lightnovel-crawler#1847]
## Let us know

**Novel URL**:     https://www.webnovel.com/book/my-dual-cultivation-system_24854289705007805
**App Location**:    EXE
**App Version**:  3.2.2

## Describe this issue

--- Logging error ---
Traceback (most recent call last):
  File "lncrawl\webdriver\local.py", line 148, in create_local
    chrome = Chrome(
  File "undetected_chromedriver\__init__.py", line 429, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 106, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 288, in __init__
  File "undetected_chromedriver\__init__.py", line 715, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 381, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 444, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 249, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:62348
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 108.0.5359.125
Stacktrace:
Backtrace:
        (No symbol) [0x008A6643]
        (No symbol) [0x0083BE21]
        (No symbol) [0x0073DA9D]
        (No symbol) [0x00762911]
        (No symbol) [0x0075A9D4]
        (No symbol) [0x0075A7B1]
        (No symbol) [0x00796917]
        (No symbol) [0x0079655C]
        (No symbol) [0x0078FB76]
        (No symbol) [0x007649C1]
        (No symbol) [0x00765E5D]
        GetHandleVerifier [0x00B1A142+2497106]
        GetHandleVerifier [0x00B485D3+2686691]
        GetHandleVerifier [0x00B4BB9C+2700460]
        GetHandleVerifier [0x00953B10+635936]
        (No symbol) [0x00844A1F]
        (No symbol) [0x0084A418]
        (No symbol) [0x0084A505]
        (No symbol) [0x0085508B]
        BaseThreadInitThunk [0x76FF00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77527BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77527B8E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1100, in emit
  File "logging\__init__.py", line 943, in format
  File "logging\__init__.py", line 678, in format
  File "logging\__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 98, in read_novel_info
    self.read_novel_info_in_browser()
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 116, in read_novel_info_in_browser
    self.visit(f"{self.home_url}{path}/catalog")
  File "lncrawl\templates\browser\basic.py", line 65, in visit
    self._visit(url)
  File "lncrawl\core\browser.py", line 155, in visit
    self._init_browser()
  File "lncrawl\core\browser.py", line 62, in _init_browser
    self._driver = create_new(
  File "lncrawl\webdriver\__init__.py", line 35, in create_new
    return create_local(
  File "lncrawl\webdriver\local.py", line 157, in create_local
    logger.exception("Failed to create chrome instance", e)
  File "logging\__init__.py", line 1512, in exception
  File "logging\__init__.py", line 1506, in error
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1704, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
Message: 'Failed to create chrome instance'
Arguments: (WebDriverException(),)
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 98, in read_novel_info
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 116, in read_novel_info_in_browser
    self.visit(f"{self.home_url}{path}/catalog")
  File "lncrawl\templates\browser\basic.py", line 65, in visit
  File "lncrawl\core\browser.py", line 155, in visit
  File "lncrawl\core\browser.py", line 62, in _init_browser
  File "lncrawl\webdriver\__init__.py", line 35, in create_new
  File "lncrawl\webdriver\local.py", line 161, in create_local
lncrawl.core.exeptions.LNException: Could not obtain a webdriver

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 88, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 82, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 72, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 122, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by drewbitt** [comment]
The error you have given is not related to Webnovel specifically but is because your ChromeDriver version and your installed version of Chrome need to match up.

`Current browser version is 108.0.5359.125`
`This version of ChromeDriver only supports Chrome version 109`

`undetected-chromedriver` should be downloading the correct version of the ChromeDriver for you according to [it's patcher class](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/dad751da18c69e3d5cf6e30a36075e2e6c81f5ec/undetected_chromedriver/patcher.py#L24). Try updating undetected-chromedriver. If that still fails, you can download the ChromeDriver manually at https://chromedriver.chromium.org/downloads for your Chrome 108

**Comment by DomID00** [comment]
> The error you have given is not related to Webnovel specifically but is because your ChromeDriver version and your installed version of Chrome need to match up.
> 
> `Current browser version is 108.0.5359.125` `This version of ChromeDriver only supports Chrome version 109`
> 
> `undetected-chromedriver` should be downloading the correct version of the ChromeDriver for you according to [it's patcher class](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/dad751da18c69e3d5cf6e30a36075e2e6c81f5ec/undetected_chromedriver/patcher.py#L24). Try updating undetected-chromedriver. If that still fails, you can download the ChromeDriver manually at https://chromedriver.chromium.org/downloads for your Chrome 108
> 
> Also see [ultrafunkamsterdam/undetected-chromedriver#939](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/939)

**Comment by DomID00** [comment]
Thank you!
