### ISSUE TITLE
Error Source Webnovel.com

### ISSUE THREAD

**Issue by DomID00** [dipu-bd/lightnovel-crawler#1886]
## Let us know

**Novel URL**:     https://www.webnovel.com/book/apocalypse-cheater_21875901505093505
**App Location**:    EXE
**App Version**:   3.2.3

## Describe this issue

? Enter novel page url or query novel: https://www.webnovel.com/book/apocalypse-cheater_21875901505093505
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "lncrawl\templates\browser\basic.py", line 88, in read_novel_info
  File "C:\Users\Byzz\AppData\Local\Temp\_MEI208002\sources\en\w\webnovel.py", line 112, in read_novel_info_in_scraper
    raise FallbackToBrowser()
lncrawl.core.exeptions.FallbackToBrowser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 95, in read_novel_info
  File "C:\Users\Byzz\AppData\Local\Temp\_MEI208002\sources\en\w\webnovel.py", line 116, in read_novel_info_in_browser
    self.visit(f"{self.home_url}{path}/catalog")
  File "lncrawl\templates\browser\basic.py", line 65, in visit
  File "lncrawl\core\browser.py", line 155, in visit
  File "lncrawl\core\browser.py", line 62, in _init_browser
  File "lncrawl\webdriver\__init__.py", line 35, in create_new
  File "lncrawl\webdriver\local.py", line 115, in create_local
  File "undetected_chromedriver\__init__.py", line 431, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 80, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 693, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:64796
from chrome not reachable
Stacktrace:
Backtrace:
        (No symbol) [0x010137D3]
        (No symbol) [0x00FA8B81]
        (No symbol) [0x00EAB230]
        (No symbol) [0x00EA0989]
        (No symbol) [0x00ECE9F2]
        (No symbol) [0x00EC70F0]
        (No symbol) [0x00EC6EE1]
        (No symbol) [0x00F01ED5]
        (No symbol) [0x00F01B2C]
        (No symbol) [0x00EFB216]
        (No symbol) [0x00ED0D97]
        (No symbol) [0x00ED253D]
        GetHandleVerifier [0x0128ABF2+2510930]
        GetHandleVerifier [0x012B8EC1+2700065]
        GetHandleVerifier [0x012BC86C+2714828]
        GetHandleVerifier [0x010C3480+645344]
        (No symbol) [0x00FB0FD2]
        (No symbol) [0x00FB6C68]
        (No symbol) [0x00FB6D4B]
        (No symbol) [0x00FC0D6B]
        BaseThreadInitThunk [0x758600F9+25]
        RtlGetAppContainerNamedObjectPath [0x774C7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x774C7B8E+238]

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by DomID00** [comment]
@dipu-bd do you have a solution please?

**Comment by dipu-bd** [comment]
Looks like this error is coming from the browser. It is failing to connect to a chrome browser instance. Check first if you have the latest Chrome installed

**Comment by dipu-bd** [comment]
Closing as a duplicate of #1810, which is the oldest open report for `webnovel.com` and is where this is tracked.

Nothing is lost by this — subscribe to #1810 for updates. If what you hit is actually a different fault on the same site rather than the same one, say so and this will be reopened.
