### ISSUE TITLE
Fix https://www.scribblehub.com : no chapters

### ISSUE THREAD

**Issue by Thrymst** [dipu-bd/lightnovel-crawler#1896]
## Let us know

:   **https://www.scribblehub.com**  <your novel url or query> 
**Discord**:    PIP | EXE | Discord | Telegram 
**Lightnovel crawler**:   x.y.z  

## Describe this issue

0 chapter from every novel

**Comment by jimster6543** [comment]
Same problem

![image_2023-02-21_111624802](https://user-images.githubusercontent.com/6154621/220400141-de6fc869-acbd-43e7-9d51-545a3b33a566.png)

**Comment by Pingger** [comment]
Issue applies to all "sources", that use Cloudflare. Interestingly a simple curl or wget does not show any issues (even when hammering with ~300 requests per minute).

Some Sources don't even have the cloudflare captcha detection yet. e.g. RoyalRoad:
```
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\<username>\AppData\Local\Temp\_MEI98682\sources\en\r\royalroad.py", line 36, in read_novel_info
    self.novel_title = soup.find("h1", {"property": "name"}).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")
```
