### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by KiraYamatoSD** [dipu-bd/lightnovel-crawler#195]
**Describe the bug**

**Let us know**
- Novel URL: https://babelnovel.com/books/top-quality-beauty-cultivation-system
- App Version: 2.14.2
- Package: pip
- OS: Windows 7

[errorlog.txt](https://github.com/dipu-bd/lightnovel-crawler/files/3599954/errorlog.txt)
 

```
================================================================================
                            Lightnovel Crawler #2.14.2
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------
                          << LOG LEVEL: WARN
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

2019-09-11 17:06:10,978 [ERROR] (DOWNLOADER)
CairoSVG was not loaded properly. SVG to PNG conversion will fail.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\lncrawl\core\downloader.py", line 19, in <module>
    from cairosvg import svg2png
  File "c:\python35\lib\site-packages\cairosvg\__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "c:\python35\lib\site-packages\cairosvg\surface.py", line 25, in <module>
    import cairocffi as cairo
  File "c:\python35\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\python35\lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
? Enter novel page url or query novel:  https://babelnovel.com/books/top-quality-beauty-cultivation
-system
Retrieving novel info...
https://babelnovel.com/books/top-quality-beauty-cultivation-system
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\lightnovel-crawler.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\lncrawl\__init__.py", line 13, in main
    start_app()
  File "c:\python35\lib\site-packages\lncrawl\core\__init__.py", line 80, in start_app
    raise err
  File "c:\python35\lib\site-packages\lncrawl\core\__init__.py", line 77, in start_app
    run_bot(bot)
  File "c:\python35\lib\site-packages\lncrawl\bots\__init__.py", line 18, in run_bot
    ConsoleBot().start()
  File "c:\python35\lib\site-packages\lncrawl\bots\console.py", line 46, in start
    self.app.get_novel_info()
  File "c:\python35\lib\site-packages\lncrawl\core\app.py", line 128, in get_novel_info
    self.crawler.read_novel_info()
  File "c:\python35\lib\site-packages\lncrawl\spiders\babelnovel.py", line 78, in read_novel_info
    for item in data['data']:
KeyError: 'data'
Press any key to continue . . .
```

**Comment by dipu-bd** [comment]
fixed. will be available in the next version
