### ISSUE TITLE
CairoSVG Failed to load.

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#199]
Soon as I start lightnovel-crawler this error comes up, I can still use program fine just thought I would let you know.

```
CairoSVG was not loaded properly. SVG to PNG conversion will fail.
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\lncrawl\core\downloader.py", line 19, in <module>
    from cairosvg import svg2png
  File "c:\python37\lib\site-packages\cairosvg\__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "c:\python37\lib\site-packages\cairosvg\surface.py", line 25, in <module>
    import cairocffi as cairo
  File "c:\python37\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\python37\lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
? Enter novel page url or query novel:
```

- Novel URL: None
- App Version: 2.14.2
- Package: PIP
- OS: Windows 10

**Comment by dipu-bd** [comment]
ignore this error. it will disappear in the next version
