### ISSUE TITLE
Fix this source

### ISSUE THREAD

**Issue by haloking4629** [dipu-bd/lightnovel-crawler#2011]
[#] Lightnovel Crawler v3.2.7
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.webnovel.com/book/i-just-inherited-the-arcane-emperor's-legacy_25932
662306661805
Retrieving novel info...
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "lncrawl\templates\browser\basic.py", line 88, in read_novel_info
  File "C:\Users\mneng\AppData\Local\Temp\_MEI243282\sources\en\w\webnovel.py", line 112, in read_novel_info_in_scraper
    raise FallbackToBrowser()
lncrawl.core.exeptions.FallbackToBrowser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 95, in read_novel_info
  File "C:\Users\mneng\AppData\Local\Temp\_MEI243282\sources\en\w\webnovel.py", line 116, in read_novel_info_in_browser
    self.visit(f"{self.home_url}{path}/catalog")
  File "lncrawl\templates\browser\basic.py", line 65, in visit
  File "lncrawl\core\browser.py", line 155, in visit
  File "lncrawl\core\browser.py", line 62, in _init_browser
  File "lncrawl\webdriver\__init__.py", line 35, in create_new
  File "lncrawl\webdriver\local.py", line 115, in create_local
  File "undetected_chromedriver\__init__.py", line 443, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 49, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 54, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 206, in __init__
  File "undetected_chromedriver\__init__.py", line 674, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 291, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 346, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: unrecognized capability: quietExceptionsStacktrace:
Backtrace:
        GetHandleVerifier [0x0101A813+48355]
        (No symbol) [0x00FAC4B1]
        (No symbol) [0x00EB5358]
        (No symbol) [0x00ECAC31]
        (No symbol) [0x00EFFCEE]
        (No symbol) [0x00EFF9A8]
        (No symbol) [0x00F00AD7]
        (No symbol) [0x00F0093C]
        (No symbol) [0x00EFA536]
        (No symbol) [0x00ED82DC]
        (No symbol) [0x00ED93DD]
        GetHandleVerifier [0x0127AABD+2539405]
        GetHandleVerifier [0x012BA78F+2800735]
        GetHandleVerifier [0x012B456C+2775612]
        GetHandleVerifier [0x010A51E0+616112]
        (No symbol) [0x00FB5F8C]
        (No symbol) [0x00FB2328]
        (No symbol) [0x00FB240B]
        (No symbol) [0x00FA4FF7]
        BaseThreadInitThunk [0x76F67D59+25]
        RtlInitializeExceptionChain [0x77D4B79B+107]
        RtlClearBits [0x77D4B71F+191]

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by zerty** [comment]
You might need to install chrome for this to work

**Comment by shagunchandel** [comment]
Done but its not working

**Comment by alzamer2** [comment]
try install selenium==4.9.0
