### ISSUE TITLE
Bug Chrome 115.0.5790.102

### ISSUE THREAD

**Issue by DomID00** [dipu-bd/lightnovel-crawler#2014]
## Let us know
since I updated chrome to Version 115.0.5790.102, problems start to appear

**Novel URL**:   https://www.webnovel.com/book/hp-the-arcane-thief_20892578405832405  <your novel url or query> 
**App Location**:    EXE 
**App Version**:   3.2.8  

## Describe this issue

================================================================================
                          [#] Lightnovel Crawler v3.2.8
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.webnovel.com/book/marvel-game-maker-system_21463505405348405
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "lncrawl\templates\browser\basic.py", line 88, in read_novel_info
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 112, in read_novel_info_in_scraper
    raise FallbackToBrowser()
lncrawl.core.exeptions.FallbackToBrowser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 95, in read_novel_info
  File "C:\Users\Byzz\.lncrawl\sources\en\w\webnovel.py", line 116, in read_novel_info_in_browser
    self.visit(f"{self.home_url}{path}/catalog")
  File "lncrawl\templates\browser\basic.py", line 65, in visit
  File "lncrawl\core\browser.py", line 155, in visit
  File "lncrawl\core\browser.py", line 62, in _init_browser
  File "lncrawl\webdriver\__init__.py", line 35, in create_new
  File "lncrawl\webdriver\local.py", line 109, in create_local
  File "lncrawl\webdriver\local.py", line 28, in _acquire_chrome_driver_path
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\drivers\chrome.py", line 40, in get_driver_download_url
  File "webdriver_manager\core\driver.py", line 51, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 62, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 37, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by alzamer2** [comment]
try to update selenium, webdriver_manager
and make sure undetected_chromedriver is 3.5
