### ISSUE TITLE
Fix this source: foxaholic

### ISSUE THREAD

**Issue by MichelleMegurine** [dipu-bd/lightnovel-crawler#2015]
**Novel URL**:     [<your novel url or query> ](https://www.foxaholic.com/novel/how-to-survive-as-a-villain/) and https://www.foxaholic.com/novel/how-to-survive-as-a-villain/1/
**App Location**:    EXE
**App Version**:   3.2.8 and Lightnovel Crawler bot

I have tried to download the novel of the links but I only get the "No chapters found error". 

#Bot message:
Got your page link
Getting information about your novel...
Failed to get novel info.
No chapters found

#EXE message: 
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Erika\AppData\Local\Temp\_MEI116482\sources\multi\foxaholic.py", line 53, in read_novel_info
    soup = self.get_soup(self.novel_url)
  File "lncrawl\core\scraper.py", line 294, in get_soup
  File "lncrawl\core\scraper.py", line 199, in get_response
  File "lncrawl\core\scraper.py", line 111, in __process_request
  File "lncrawl\core\scraper.py", line 104, in __process_request
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.foxaholic.com/novel/how-to-survive-as-a-villain/

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

**Comment by dipu-bd** [comment]
Duplicate of #1907, which is the oldest open report for `foxaholic.com` and where this is tracked.

Closing here to keep one thread per broken source — the problem itself stays open. If you have detail the other issue does not (a novel url that fails, the error text, when it last worked), please add it there; that is what makes these fixable.
