### ISSUE TITLE
Fix this source novelsemperor.com

### ISSUE THREAD

**Issue by DomID00** [dipu-bd/lightnovel-crawler#2046]
They changed their theme, so it can't find any chapters anymore

https://novelsemperor.com/

**Comment by zGadli** [comment]
Thr crawler file for this source isn't properly written. Someone should check it out.

**Comment by DomID00** [comment]
@zerty it seems to have a problem for the chapters page when I download inside the .txt it says "Failed to download chapter body"

**Comment by zGadli** [comment]
@DomID00 What about other formats?

**Comment by DomID00** [comment]
@zGadli I don't know, I only use the .txt, but I solved the problem, I just had to change the "div" `mx-auto.max-w-3xl`

`    def select_chapter_body(self, soup: BeautifulSoup) -> Tag:
        return soup.select_one(
            "#readernovel, #readerarea, .entry-content,.chap-content,.mx-auto.max-w-3xl"
        )`

`    def visit_chapter_page_in_browser(self, chapter: Chapter) -> None:
        self.visit(chapter.url)
        self.browser.wait(
            "#readernovel, #readerarea, .entry-content,.mainholder,.chap-content,.mx-auto.max-w-3xl"
        )`

**Comment by DomID00** [comment]
@zGadli I also noticed that there are novels that the script does not detect, so throws the error of no chapters, but the novel in question has many chapters

for example this novel: https://novelsemperor.com/series/comprehensive-martial-arts-prince-qin-you-practice-martial-arts-while-i-cultivate-immortals

**Comment by zGadli** [comment]
@DomID00 If the error code is 403 then they are refusing because of server request spam. Use `python lncrawl -lll` to find where the error is originating from.

**Comment by DomID00** [comment]
@zGadli here is the error i got :

```
? Enter novel page url or query novel: https://novelsemperor.com/series/comprehensive-martial-arts-prince-qin-you-pract
ice-martial-arts-while-i-cultivate-immortals
01:32:58 [INFO] (lncrawl.bots.console.integration)
Detected URL input
01:32:58 [INFO] (lncrawl.core.sources)
Initializing crawler for: https://novelsemperor.com/ [C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\sources\en\n\novelsemperor.py]
Retrieving novel info...
01:32:58 [DEBUG] (lncrawl.core.scraper)
[GET] https://novelsemperor.com/series/comprehensive-martial-arts-prince-qin-you-practice-martial-arts-while-i-cultivate-immortals
timeout=(7, 301), allow_redirects=True, proxies={}, headers={b'Origin': b'https://novelsemperor.com', b'Referer': b'https://novelsemperor.com/', b'User-Agent': b'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:105.0) Gecko/20100101 Firefox/105.0'}
01:32:58 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): novelsemperor.com:443
01:33:00 [DEBUG] (urllib3.connectionpool)
https://novelsemperor.com:443 "GET /series/comprehensive-martial-arts-prince-qin-you-practice-martial-arts-while-i-cultivate-immortals HTTP/1.1" 200 None

 ! Error: No chapters found
<class 'Exception'>
File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

01:33:00 [INFO] (lncrawl.core.app)
App destroyed
```

**Comment by zGadli** [comment]
It seems that the crawler that is written for this source is not complete. I'll see what i can do.

**Comment by DomID00** [comment]
@zGadli using your modification on it no longer recognizes the site

```
Module load failed: C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\sources\en\n\novelsemperor.py | invalid syntax (novelsemperor.py, line 1)

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://novelsemperor.com/series/comprehensive-martial-arts-prince-qin-you-pract
ice-martial-arts-while-i-cultivate-immortals

 ! Sorry! I do not recognize this website yet.
```

**Comment by zGadli** [comment]
@DomID00 Any updates. Also, I updated my pr.

**Comment by DomID00** [comment]
@zGadli I used the update, but still a problem

```
14:26:35 [DEBUG] (lncrawl.core.sources)
Saving current index data to C:\Users\Byzz\.lncrawl\sources\_index.json
14:26:35 [DEBUG] (lncrawl.core.sources)
Saving current index data to C:\Users\Byzz\.lncrawl\sources\_index.json
14:26:35 [WARNING] (lncrawl.core.sources)
Module load failed: C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\sources\en\n\novelsemperor.py | invalid syntax (novelsemperor.py, line 1)

-> Press  Ctrl + C  to exit

14:26:36 [INFO] (lncrawl.core.app)
Initialized App
14:26:36 [DEBUG] (asyncio)
Using proactor: IocpProactor
? Enter novel page url or query novel: https://novelsemperor.com/series/chat-group-my-strength-is-the-sum-of-my-friends

14:26:49 [INFO] (lncrawl.bots.console.integration)
Detected URL input

 ! Sorry! I do not recognize this website yet.

Find the list of supported/rejected sources here:
 - https://github.com/dipu-bd/lightnovel-crawler#supported-sources

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 57, in start
    self.app.crawler = prepare_crawler(self.app.user_input)
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\sources.py", line 360, in prepare_crawler
    raise LNException("No crawler found for " + base_url)
lncrawl.core.exeptions.LNException: No crawler found for https://novelsemperor.com/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\__main__.py", line 15, in <module>
    main()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\__init__.py", line 16, in main
    start_app()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\__init__.py", line 68, in start_app
    run_bot(bot)
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\__init__.py", line 16, in run_bot
    ConsoleBot().start()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 61, in start
    logger.debug("Trying to find it in novelupdates", e)
Message: 'Trying to find it in novelupdates'
Arguments: (LNException('No crawler found for https://novelsemperor.com/'),)
14:26:49 [DEBUG] (lncrawl.core.scraper)
[GET] https://novelsemperor.com/series/chat-group-my-strength-is-the-sum-of-my-friends
timeout=(7, 301), allow_redirects=True, proxies={}, headers={b'Origin': b'https://novelsemperor.com/series/chat-group-my-strength-is-the-sum-of-my-friends', b'Referer': b'https://novelsemperor.com/series/chat-group-my-strength-is-the-sum-of-my-friends', b'User-Agent': b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
14:26:49 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): novelsemperor.com:443
14:26:50 [DEBUG] (urllib3.connectionpool)
https://novelsemperor.com:443 "GET /series/chat-group-my-strength-is-the-sum-of-my-friends HTTP/1.1" 200 None

 * You can search novelupdates to find this novel!

? Enter novelupdates query: Chat group: My strength is the sum of my friends
```

**Comment by zGadli** [comment]
@DomID00 I tried on my PC and everything is working fine. So I don't know where the error is coming from.

**Comment by zGadli** [comment]
@DomID00 Fork from my repo dev branch and try again.

**Comment by DomID00** [comment]
@zGadli weird, its telling me there is a problem with invalid syntax in the first line.
look at the code I wrote it well right?

```
@@ -1,8 +1,8 @@
# -*- coding: utf-8 -*-
import logging
import re
from lncrawl.templates.mangastream import MangaStreamTemplate

logger = logging.getLogger(__name__)
search_url = 'https://novelsemperor.com/series?title=%s&type=&status='

class NovelsEmperorCrawler(MangaStreamTemplate):
    base_url = ["https://novelsemperor.com/"]
	
    def initialize(self) -> None:
        self.cleaner.bad_text_regex.update(
            [
                "Thank you for reading this story at novelsemperor.com",
                "immediately rushed \\(Campaign period:",
                "promotion, charge 100 and get 500 VIP coupons!",
            ]
        )
		
    def search_novel(self, query):
        query = query.lower().replace(" ", "+")
        soup = self.get_soup(search_url % query)
		
        results = []
        for tab in soup.select("div.xlg\\:grid-cols-8.grid.grid-cols-3 div#card-real"):
            a = tab.select_one("a")
            title = a["href"][33:].replace('-', ' ')
            img = tab.select_one("img")["data-src"]
            results.append(
                {
                    "title": title,
                    "url": self.absolute_url(a["href"]),
                    "img": img,
                }
            )
			
        return results

    def read_novel_info(self):
        logger.debug("Visiting %s", self.novel_url)
        pagination_num = self.get_soup(self.novel_url)
        pagination_num = pagination_num.select_one("ul > li:nth-last-child(2)").text
        pagination_num = int(pagination_num)

        soup = []

        for i in range(1, pagination_num + 1):
            soup.append(self.get_soup(f'{self.novel_url}?page={i}'))

        possible_title = soup[0].select_one("h2.text-2xl")
        assert possible_title, "No novel title"
        logger.info("Novel title: %s", self.novel_title)

        author = soup[0].select('p:nth-child(4) > span.capitalize')
        if len(author) == 2:
            self.novel_author = author[0].text + " (" + author[1].text + ")"
        else:
            self.novel_author = author[0].text
        logger.info("Novel author: %s", self.novel_author)

        self.novel_cover = self.absolute_url(
            soup[0].select_one("div.relative > img")["src"]
        )
        logger.info("Novel cover: %s", self.novel_cover)

        for i in range(len(soup) - 1, -1, -1):
            for div in soup[i].select("div#chapters-list"):
                vol_title = div.select_one("a div div span").text
                vol_id = [int(x) for x in re.findall(r"\d+", vol_title)]
                vol_id = vol_id[0] if len(vol_id) else len(self.volumes) + 1
                self.volumes.append(
                    {				
                        "id": vol_id,
                        "title": vol_title,
                    }
                )

                for a in div.select("a"):
                    ch_title = a.select_one("div div span").text
                    ch_id = [int(x) for x in re.findall(r"\d+", ch_title)]
                    ch_id = ch_id[0] if len(ch_id) else len(self.chapters) + 1
                    self.chapters.append(
                        {
                            "id": ch_id,
                            "volume": vol_id,
                            "title": ch_title,
                            "url": self.absolute_url(a["href"]),
                        }
                    )

        logger.debug(
            "%d chapters and %d volumes found", len(self.chapters), len(self.volumes)
        )
    def download_chapter_body(self, chapter):
        soup = self.get_soup(chapter["url"])
        contents = soup.select_one("div.mx-auto.max-w-3xl")
        return str(contents)
```

**Comment by zGadli** [comment]
@DomID00 try removing the comment. The imports seem fine to me.

**Comment by zGadli** [comment]
@DomID00 ok I will check the latest commit. What novel are you reading on this source.

**Comment by zGadli** [comment]
@DomID00 I just deleted my local repo and cloned it again. It works fine. I think this might have something to do with your python version or Operating System. Please check and reply.
