### ISSUE TITLE
Fix this source : https://www.mtlnovel.com/

### ISSUE THREAD

**Issue by alisanbox** [dipu-bd/lightnovel-crawler#2132]
## Let us know

**Novel URL**:   https://www.mtlnovel.com/dimensional-invasion-of-the-real-earth/
**App Location**:     EXE (Win 10 64bit)
**App Version**:   [#] Lightnovel Crawler v3.3.0

## Describe this issue

! Error: No chapters found

 Enter novel page url or query novel: https://www.mtlnovel.com/dimensional-invasion-of-the-real-earth
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\WINDOW~1\AppData\Local\Temp\_MEI59082\sources\multi\mtlnovel.py", line 47, in read_novel_info
    soup = self.get_soup(self.novel_url)
  File "lncrawl\core\scraper.py", line 296, in get_soup
  File "lncrawl\core\scraper.py", line 201, in get_response
  File "lncrawl\core\scraper.py", line 130, in __process_request
  File "lncrawl\core\scraper.py", line 123, in __process_request
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://www.mtlnovel.com/dimensional-invasion-of-the-real-earth

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by CryZFix** [comment]
It seems that there is a problem with one of their sent headers, an access attempt outside of crawler has a status of 200.
I'm not sure I'm digging in the right direction yet, maybe someone more experienced should take a look at this.
```
>>> import requests
>>> headers = {"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1"}
>>> response = requests.get("https://www.mtlnovel.com/dimensional-invasion-of-the-real-earth/", headers=headers)
>>> response
<Response [200]>
```
