### ISSUE TITLE
Novelsemperor "No chapters found"

### ISSUE THREAD

**Issue by DomID00** [dipu-bd/lightnovel-crawler#2165]
here is the error I get for novelsemperor.com 

--------------------------------

                          [#] Lightnovel Crawler v3.2.8
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------
 $ VERSION 3.3.0 IS NOW AVAILABLE!
  -> Upgrade using pip install -U lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://novelsemperor.com/series/at-the-beginning-of-the-game-there-will-be-1000
00-dead-soldiers-and-a-group-will-go-to-yingjiang-to-buy-it-for-zero-yuan
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Byzz\.lncrawl\sources\en\n\novelsemperor.py", line 43, in read_novel_info
    pagination_num = self.get_soup(self.novel_url)
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\scraper.py", line 294, in get_soup
    response = self.get_response(url, **kwargs)
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\scraper.py", line 199, in get_response
    return self.__process_request(
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\scraper.py", line 111, in __process_request
    raise e
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\scraper.py", line 104, in __process_request
    response.raise_for_status()
  File "C:\Users\Byzz\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://novelsemperor.com/series/at-the-beginning-of-the-game-there-will-be-100000-dead-soldiers-and-a-group-will-go-to-yingjiang-to-buy-it-for-zero-yuan

 ! Error: No chapters found
<class 'Exception'>
File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "C:\Users\Byzz\Desktop\lightnovel-crawler-3.2.8\lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

--------------------------------------------------------------------------------
 -  https://github.com/dipu-bd/lightnovel-crawler/issues
================================================================================

**Comment by Alla183** [comment]
solution ? please

**Comment by dipu-bd** [comment]
Duplicate of #1897, which is the oldest open report for `novelsemperor.com` and where this is tracked.

Closing here to keep one thread per broken source — the problem itself stays open. If you have detail the other issue does not (a novel url that fails, the error text, when it last worked), please add it there; that is what makes these fixable.
