### ISSUE TITLE
Fix this source https://www.foxaholic.com/

### ISSUE THREAD

**Issue by Samsara-byte** [dipu-bd/lightnovel-crawler#2328]
yes, but not fixing.
## Let us know

**Novel URL**:    [ [<your novel url or query> ](https://www.foxaholic.com/)](https://www.foxaholic.com/novel/i-was-caught-up-in-a-hero-summoning-but-that-world-is-at-peace/)
**App Location**:    PIP  
**App Version**:   x.y.z  

## Describe this issue

when ı tried download the novel. no chapter found error happen.

Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/sources/multi/foxaholic.py", line 53, in read_novel_info
    soup = self.get_soup(self.novel_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/core/scraper.py", line 306, in get_soup
    response = self.get_response(url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/core/scraper.py", line 201, in get_response
    return self.__process_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/core/scraper.py", line 130, in __process_request
    raise e
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/core/scraper.py", line 123, in __process_request
    response.raise_for_status()
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.foxaholic.com/novel/i-was-caught-up-in-a-hero-summoning-but-that-world-is-at-peace/

 ❗ Error: No chapters found 
<class 'Exception'>
File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 107, in start
    raise e
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 101, in start
    _download_novel()
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "/home/ancient/Documents/lncrawl/env/lib/python3.11/site-packages/lncrawl/core/app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

**Comment by dipu-bd** [comment]
Duplicate of #1907, which is the oldest open report for `foxaholic.com` and where this is tracked.

Closing here to keep one thread per broken source — the problem itself stays open. If you have detail the other issue does not (a novel url that fails, the error text, when it last worked), please add it there; that is what makes these fixable.
