### ISSUE TITLE
https://es.mtlnovel.com/

### ISSUE THREAD

**Issue by Opicuss** [dipu-bd/lightnovel-crawler#2391]
? Enter novel page url or query novel: https://es.mtlnovel.com/galactic-garbage-station/
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\XXXX\AppData\Local\Temp\_MEI163122\sources\multi\mtlnovel.py", line 50, in read_novel_info
    soup = self.get_soup(self.novel_url)
  File "lncrawl\core\scraper.py", line 306, in get_soup
  File "lncrawl\core\scraper.py", line 201, in get_response
  File "lncrawl\core\scraper.py", line 130, in __process_request
  File "lncrawl\core\scraper.py", line 123, in __process_request
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://es.mtlnovel.com/galactic-garbage-station/

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

**Comment by zGadli** [comment]
It's because of Cloudflare. I would recommend trying to find another source.

**Comment by Opicuss** [comment]
I tried version 350 and it is working there
