### ISSUE TITLE
Error _csrfToken webnovel.com

### ISSUE THREAD

**Issue by YSaitOz** [dipu-bd/lightnovel-crawler#2459]
-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.webnovel.com/book/i'm-bombarding-the-supernatural-world-with-my-fire
arms_29917267208875605
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "lncrawl\templates\browser\basic.py", line 88, in read_novel_info
  File "C:\Users\Allan\AppData\Local\Temp\_MEI128442\sources\en\w\webnovel.py", line 69, in read_novel_info_in_scraper
    self.get_csrf()
  File "C:\Users\Allan\AppData\Local\Temp\_MEI128442\sources\en\w\webnovel.py", line 36, in get_csrf
    self.csrf = self.cookies["_csrfToken"]
KeyError: '_csrfToken'

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

Press ENTER to exit...

**Comment by YSaitOz** [comment]
Does anyone know how to resolve this error?
