### ISSUE TITLE
Creativenovels spider can't find chapters

### ISSUE THREAD

**Issue by tidux** [dipu-bd/lightnovel-crawler#246]
**Describe the bug**
When given a valid novel link, 0 chapters are found, but 231 chapters exist.  

**Let us know**
- Novel URL: https://creativenovels.com/novel/kusuriya-no-hitorigoto/
- App Version: 2.16.2
- Package: pip
- OS: MacOS Mojave

**Comment by tidux** [comment]
Confirmed to exist on Debian 10 amd64 as well.

**Comment by tidux** [comment]
I think the spider is failing to find the shortlink, since that includes links to all the chapters in a crawlable layout.

https://creativenovels.com/80/

**Comment by tidux** [comment]
```
Traceback (most recent call last):
  File "/Users/tidux/Library/Python/3.7/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/__init__.py", line 13, in main
    start_app()
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/core/__init__.py", line 80, in start_app
    raise err
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/core/__init__.py", line 77, in start_app
    run_bot(bot)
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/bots/__init__.py", line 18, in run_bot
    ConsoleBot().start()
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/bots/console.py", line 65, in start
    self.app.chapters = self.process_chapter_range()
  File "/Users/tidux/Library/Python/3.7/lib/python/site-packages/lncrawl/bots/console.py", line 118, in process_chapter_range
    raise Exception('No chapters to download')
Exception: No chapters to download
```

**Comment by tidux** [comment]
Looks like they broke pagination on the shortlinks.  New strategy for finding chapters:

Profile page link to chapter 1 => `<div class="btn-lib-new"><a href="https://creativenovels.com/80/volume-1-chapter-1-maomao/">`

Chapter 1 link to chapter 2 => `<a class="x-btn nextkey x-btn-global x-btn-icon-only" href="https://creativenovels.com/80/volume-1-chapter-2-the-two-consorts/" data-options="thumbnail: ''">`

The links are deliberately obfuscated and aren't visible without JavaScript running, but those class patterns do seem to hold across multiple novels and chapters.

**Comment by tidux** [comment]
Fixed.

https://github.com/dipu-bd/lightnovel-crawler/pull/247

**Comment by dipu-bd** [comment]
thanks for fixing it @tidux
