### ISSUE TITLE
Problem with ncode.syosetu.com/n5619fv

### ISSUE THREAD

**Issue by Demorao** [dipu-bd/lightnovel-crawler#2509]
## Describe the bug

When I try to download a novel from the syosetu page, it gives an error

Enter novel page url or query novel: https://ncode.syosetu.com/n5619fv/
Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\demor\AppData\Local\Temp\_MEI621962\sources\jp\s\syosetu.py", line 41, in read_novel_info
    self.novel_title = soup.select_one(".novel_title").text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

## Let us know

**App source**:    EXE
**App version**:   3.7.2
**Your OS**:        Windows

**Comment by zGadli** [comment]
Close issue. It will be fixed in next update.
