### ISSUE TITLE
Fix www.xbanxia.com

### ISSUE THREAD

**Issue by ecl95** [dipu-bd/lightnovel-crawler#2520]
Yes, no one else has raised an issue yet? I tried remaking the 
## Let us know

**Novel URL**:     [嫁给残疾皇子后](https://www.xbanxia.com/books/143300.html)
**App Location**:    PIP | EXE | Discord | Telegram 
PIP 

**App Version**:   3.7.3 

## Describe this issue

Xbanxia won't download, it says that no chapters are found. 

Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "/Users/user_1/opt/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/Users/user_1/opt/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/sources/zh/xbanxia.py", line 43, in read_novel_info
    soup = self.get_soup(self.novel_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/core/scraper.py", line 306, in get_soup
    response = self.get_response(url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/core/scraper.py", line 201, in get_response
    return self.__process_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/core/scraper.py", line 130, in __process_request
    raise e
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/core/scraper.py", line 123, in __process_request
    response.raise_for_status()
  File "/Users/user_1/opt/anaconda3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.xbanxia.com/books/279422.html
 ❗ Error: No chapters found 
<class 'Exception'>
File "/Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/bots/console/integration.py", line 107, in start
    raise e
  File "/Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/bots/console/integration.py", line 101, in start
    _download_novel()
  File "/Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/bots/console/integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "/Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/lncrawl/core/app.py", line 137, in get_novel_info
    raise Exception("No chapters found")
-----------------------------------------------

Admittedly, there are other problems with my installation, namely: 
Module load failed: /Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/sources/zh/czbooks.py | inconsistent use of tabs and spaces in indentation (czbooks.py, line 45)
Module load failed: /Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/sources/ar/rewayatclub.py | 3
Module load failed: /Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/sources/en/r/ranobes.py | 3
Module load failed: /Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/sources/en/n/novelmao.py | 3
Module load failed: /Users/Elaine_1/opt/anaconda3/lib/python3.12/site-packages/sources/en/l/lnmtl.py | 3

but I've been able to use lncrawl fine for other websites, so I believe it is site specific. 

Thanks in advance for your time and help

**Comment by zGadli** [comment]
Use the latest version of the app. Close the issue if resolved.

**Comment by ecl95** [comment]
This was fixed and now the error is back.
