### ISSUE TITLE
Babelnovel links are showing "cssUrl" error

### ISSUE THREAD

**Issue by 13kirito** [dipu-bd/lightnovel-crawler#263]
All the links i tried from Babelnovel are showing the same
- Novel URL: https://babelnovel.com/books/against-the-gods

- App Version: 2.17.0
- Package: pip and bot
- OS: Windows 8.1

![babelnovel issue](https://user-images.githubusercontent.com/55593373/70393131-1fe1a500-1a0d-11ea-9ec5-b6079e42f9ea.jpg)

**Comment by dipu-bd** [comment]
Try other sources for now. I am doing a refactoring on babelnovel

**Comment by dipu-bd** [comment]
they removed the `cssUrl` tag from `window.__STATE__`. I ignored the errors for now to fix it.

**Comment by 13kirito** [comment]
> they removed the `cssUrl` from `window.__STATE__`. I ignored the errors for now to fix it.

yeah it started working, Thanks.
For some chapters its showing:

"TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/against-the-gods/chapters/c89"

but trying to download the same volume a few times completes the download.
Some novel links are still not showing complete chapters which was working well with 2.17.0 version.
Solving the cssUrl error might fix it.
See if u can fix it, though its working fine for most of the other novels.
No hurry..
Thanks.

**Comment by Flwk** [comment]
```
`  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4220
Downloading chapters |███████████████████████████     | 221/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4221
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4222
Downloading chapters |████████████████████████████    | 223/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4224
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4223
Downloading chapters |████████████████████████████    | 225/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4225
Downloading chapters |████████████████████████████    | 226/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4226
Downloading chapters |████████████████████████████    | 227/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4227
Downloading chapters |████████████████████████████    | 228/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4228
Downloading chapters |████████████████████████████    | 229/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4229
Downloading chapters |████████████████████████████    | 230/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4230
Downloading chapters |████████████████████████████    | 231/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4231
Downloading chapters |█████████████████████████████   | 232/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4232
Downloading chapters |█████████████████████████████   | 233/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4233
Downloading chapters |█████████████████████████████   | 234/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4234
Downloading chapters |█████████████████████████████   | 235/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4235
Downloading chapters |█████████████████████████████   | 236/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4236
Downloading chapters |█████████████████████████████   | 237/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4237
Downloading chapters |█████████████████████████████   | 238/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4238
Downloading chapters |█████████████████████████████   | 239/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4239
Downloading chapters |██████████████████████████████  | 240/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4240
Downloading chapters |██████████████████████████████  | 241/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4242
Downloading chapters |██████████████████████████████  | 242/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4241
Downloading chapters |██████████████████████████████  | 243/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4243
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4244
Downloading chapters |██████████████████████████████  | 245/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4246
Downloading chapters |██████████████████████████████  | 246/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4245
Downloading chapters |██████████████████████████████  | 247/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4248
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4247
Downloading chapters |███████████████████████████████ | 249/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4249
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4250
Downloading chapters |███████████████████████████████ | 251/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4252
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4251
Downloading chapters |███████████████████████████████ | 253/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Failed to download chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4254
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4253
Downloading chapters |███████████████████████████████ | 255/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4256
Downloading chapters |████████████████████████████████| 256/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4255
Downloading chapters |████████████████████████████████| 257/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4257
Downloading chapters |████████████████████████████████| 258/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4258
Downloading chapters |████████████████████████████████| 259/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4259
Downloading chapters |████████████████████████████████| 260/261Failed to downloa
d chapter body
Traceback (most recent call last):
  File "src\core\downloader.py", line 115, in download_chapter_body
  File "src\spiders\babelnovel.py", line 143, in download_chapter_body
TypeError: string indices must be integers
Body is empty: https://babelnovel.com/books/martial-god-asura/chapters/c4260
Downloading chapters |████████████████████████████████| 261/261
←[?25hDownloaded 261 chapters
Failed to generate "epub": Document is empty
Traceback (most recent call last):
  File "src\binders\__init__.py", line 62, in generate_books
  File "src\binders\epub.py", line 165, in make_epubs
  File "src\binders\epub.py", line 152, in bind_epub_book
  File "venv\lib\site-packages\ebooklib\epub.py", line 1717, in write_epub
  File "venv\lib\site-packages\ebooklib\epub.py", line 1364, in write
  File "venv\lib\site-packages\ebooklib\epub.py", line 1351, in _write_items
  File "venv\lib\site-packages\ebooklib\epub.py", line 1207, in _get_nav
  File "venv\lib\site-packages\ebooklib\utils.py", line 118, in get_pages_for_it
ems
  File "venv\lib\site-packages\ebooklib\utils.py", line 118, in <listcomp>
  File "venv\lib\site-packages\ebooklib\utils.py", line 95, in get_pages
  File "venv\lib\site-packages\ebooklib\utils.py", line 47, in parse_html_string

  File "venv\lib\site-packages\lxml\html\__init__.py", line 764, in document_fro
mstring
lxml.etree.ParserError: Document is empty
* Task completed`
```

Here is the erros i have when i try to download a novel

**Comment by dipu-bd** [comment]
I see you are trying to download Martial God Asura. But the notice on the website says it was removed from Babelnovel due to the request of the publisher.
