### ISSUE TITLE
https://listnovel.com/

### ISSUE THREAD

**Issue by KiraYamatoSD** [dipu-bd/lightnovel-crawler#269]

**Comment by KiraYamatoSD** [comment]
Hi, Thanks for the update.  

After testing, I have found one URL seems to be not working and throw out an error.

```

Z:\>lightnovel-crawler -lll --multi --all --ignore --add-
source-url --suppress --format "epub" --source "https://listnovel.com/novel/empress-of-otherverse/"
--output "./Empress Of Otherverse"
================================================================================
                            Lightnovel Crawler #2.19.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------
                          << LOG LEVEL: DEBUG
--------------------------------------------------------------------------------
 ! Input is suppressed
--------------------------------------------------------------------------------
Namespace(add_source_url=True, all=True, bot=None, chapters=None, extra={}, filename=None, filename_
only=False, first=None, force=False, ignore=True, last=None, list_sources=False, log=3, login=None,
multi=True, novel_page='https://listnovel.com/novel/empress-of-otherverse/', output_formats=['epub']
, output_path='./Empress Of Otherverse', page=None, query=N
one, range=None, single=False, sources=False, suppress=True, volumes=None)
2020-01-07 05:18:40,307 [DEBUG] (urllib3.connectionpool)
Starting new HTTP connection (1): bit.ly:80
2020-01-07 05:18:41,399 [DEBUG] (urllib3.connectionpool)
http://bit.ly:80 "GET /2yYyFGd HTTP/1.1" 301 132
2020-01-07 05:18:41,415 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): pypi.org:443
2020-01-07 05:18:43,287 [DEBUG] (urllib3.connectionpool)
https://pypi.org:443 "GET /pypi/lightnovel-crawler/json HTTP/1.1" 200 16153

-> Press  Ctrl + C  to exit

2020-01-07 05:18:44,036 [WARNING] (DOWNLOADER)
CairoSVG was not loaded properly. SVG to PNG conversion will fail.
2020-01-07 05:18:44,051 [INFO] (APP)
Initialized App
2020-01-07 05:18:44,051 [INFO] (APP)
Detected URL input
2020-01-07 05:18:44,051 [INFO] (APP)
Initializing crawler for: https://listnovel.com/
Retrieving novel info...
https://listnovel.com/novel/empress-of-otherverse/
2020-01-07 05:18:44,051 [DEBUG] (LIST_NOVEL)
Visiting https://listnovel.com/novel/empress-of-otherverse/
2020-01-07 05:18:44,051 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): listnovel.com:443
2020-01-07 05:18:46,766 [DEBUG] (urllib3.connectionpool)
https://listnovel.com:443 "GET /novel/empress-of-otherverse/ HTTP/1.1" 200 19991
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\lightnovel-crawler.exe\__main__.py", line 7, in <module>
  File "c:\python35\lib\site-packages\lncrawl\__init__.py", line 13, in main
    start_app()
  File "c:\python35\lib\site-packages\lncrawl\core\__init__.py", line 79, in start_app
    raise err
  File "c:\python35\lib\site-packages\lncrawl\core\__init__.py", line 76, in start_app
    run_bot(bot)
  File "c:\python35\lib\site-packages\lncrawl\bots\__init__.py", line 17, in run_bot
    ConsoleBot().start()
  File "c:\python35\lib\site-packages\lncrawl\bots\console\start.py", line 57, in start
    self.app.get_novel_info()
  File "c:\python35\lib\site-packages\lncrawl\core\app.py", line 129, in get_novel_info
    self.crawler.read_novel_info()
  File "c:\python35\lib\site-packages\lncrawl\sources\listnovel.py", line 20, in read_novel_info
    possible_title.find('span').extract()
AttributeError: 'NoneType' object has no attribute 'extract'



```
