### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character '\xa0' in position 48: illegal multibyte sequence

### ISSUE THREAD

**Issue by AvatarWan** [dipu-bd/lightnovel-crawler#30]
[?25hCreated: I’m in Hollywood.epub
Failed to generate mobi for I’m in Hollywood.epub
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\lightnovel-crawler.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\lightnovel_crawler\__init__.py", line 65, in main
    start_app(crawler_list)
  File "c:\program files (x86)\python36-32\lib\site-packages\lightnovel_crawler\app\__init__.py", line 34, in start_app
    Program().run(crawler())
  File "c:\program files (x86)\python36-32\lib\site-packages\lightnovel_crawler\app\program.py", line 38, in run
    bind_books(self)
  File "c:\program files (x86)\python36-32\lib\site-packages\lightnovel_crawler\app\bind_books.py", line 56, in bind_books
    file.write(text)
UnicodeEncodeError: 'cp932' codec can't encode character '\xa0' in position 48: illegal multibyte sequence

**Comment by AvatarWan** [comment]
on downloading https://www.readlightnovel.org/i-m-in-hollywood/ this error come
most likely by using 'utf-8' on like number 51 of app/bind_book.py as

with open(file_name, 'w',encoding="utf-8") as file:

**Comment by dipu-bd** [comment]
it is fixed in the latest version. install the latest one using:

```
$ python3 -m pip install --user -U lightnovel-crawler
```
