### ISSUE TITLE
Hangs on Searching

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#350]
So with the latest version when I try and search for **Peerless Battle Spirit** it starts to search and gets stuck on 21/22. I left it like that for 4 minutes and 35 seconds before it showed results. When I use older version it works within seconds to bring up search results. I'm not sure what's causing it.

**Update**
After trying download book it comes up with a massive error.

```
Downloading chapters |█                               | 34/1564Failed to download chapter body
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "c:\python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "c:\python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "c:\python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "c:\python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\python37\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "c:\python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "c:\python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "c:\python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "c:\python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\lncrawl\core\downloader.py", line 118, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python37\lib\site-packages\lncrawl\sources\wuxiaco.py", line 99, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python37\lib\site-packages\lncrawl\utils\crawler.py", line 190, in get_soup
    response = self.get_response(*args, **kargs)
  File "c:\python37\lib\site-packages\lncrawl\utils\crawler.py", line 158, in get_response
    response = self.scrapper.get(url, **kargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\python37\lib\site-packages\lncrawl\utils\cfscrape.py", line 124, in request
    method, url, *args, **kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Body is empty: https://www.wuxiaworld.co/Peerless-Battle-Spirit/1491052.html
Downloading chapters |███                             | 143/1564     
```

- Novel Search: Peerless Battle Spirit
- App Version: 2.19.4
- Package: PIP
- OS: Windows 10

**Comment by drewbitt** [comment]
I am getting this too with all searches today and yesterday. I thought there was supposed to be a 1.5 minute timeout (way too big for a search imo) but that doesn't seem to be the case.

Your download book issue should be a separate issue though, no?

**Comment by SirGryphin** [comment]
Tried the same book with another source and it seems to of downloaded okay, so maybe it was site timing out.

**Comment by dipu-bd** [comment]
cloudflare enabled sites are slow and error-prone. searching always gets stuck in these sites. i will do something about it.

**Comment by dipu-bd** [comment]
#353 should fix this issue
