### ISSUE TITLE
https://mangatoon.mobi/

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#510]

**Comment by dipu-bd** [comment]
When downloading chapters:

```
Traceback (most recent call last):
  File "./lncrawl/core/downloader.py", line 122, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "./lncrawl/sources/mangatoon.py", line 71, in download_chapter_body
    initialValue = re.search('var initialValue = (?P<value>.*);', script.string)
AttributeError: 'NoneType' object has no attribute 'string'
Body is empty: https://mangatoon.mobi/en/watch/260153/127042
```

Example: https://mangatoon.mobi/en/detail/260153

**Comment by yudilee** [comment]
only works on novel, because that site also provide comic/manga

**Comment by dipu-bd** [comment]
got it. closing this issue then
