### ISSUE TITLE
Issue with launching from terminal

### ISSUE THREAD

**Issue by RyanLiu6** [dipu-bd/lightnovel-crawler#512]
**Describe the bug**
After upgrading to the latest version on pip (2.22.0), the command itself no longer works. Temporarily, I have manually downgraded to 2.21.0 as a workaround.

```
$ lncrawl
Traceback (most recent call last):
  File "/Users/ryanl/.pyenv/versions/3.7.5/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/__init__.py", line 12, in main
    from .core import start_app
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/core/__init__.py", line 15, in <module>
    from ..utils.update_checker import check_updates
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/utils/update_checker.py", line 7, in <module>
    from ..core.display import new_version_news
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/core/display.py", line 10, in <module>
    from ..sources import crawler_list
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/sources/__init__.py", line 61, in <module>
    module = importlib.import_module('.' + module_name, package=__package__)
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/ryanl/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lncrawl/sources/novelfull.py", line 99
    if pc and (match := re.search(RE_VOLUME, title, re.IGNORECASE)):
                     ^
SyntaxError: invalid syntax
```

**Let us know**
- Novel URL: N/A
- App Version: `lightnovel-crawler==2.22.0`
- Package: pip
- OS: macOS 10.15

**Comment by dipu-bd** [comment]
Fixed on v2.22.1
