### ISSUE TITLE
Downloads fail for royalroad

### ISSUE THREAD

**Issue by Achtland** [dipu-bd/lightnovel-crawler#662]
lncrawl doesn't download all chapters from royalroad novels, due to a HTTP error 429. Upgrading to the newest version of lncrawl (from Oct 2020) didn't help.
Terminal error message (from linux bash):
1 volumes and 29 chapters found
Downloading chapters |██████████████▍                 | 13/29Failed to download chapter body
Traceback (most recent call last):
  File "lncrawl/core/downloader.py", line 122, in download_chapter_body
  File "lncrawl/sources/royalroad.py", line 85, in download_chapter_body
  File "lncrawl/utils/crawler.py", line 196, in get_soup
  File "lncrawl/utils/crawler.py", line 169, in get_response
  File "venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests

Workaround: Run lncrawl several times to get missing chapters. This might take some time with bigger novels.

**Comment by d1st4nt** [comment]
I've experienced the same.  This is a rate limit issue.  I've found not interacting with RR at all when downloading from RR resolves the issue 9/10 times.

**Comment by yudilee** [comment]
i tried this many times but not experiencing this problem

**Comment by dipu-bd** [comment]
closing it since could not reproduce the issue
