### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by HarmonLucifer** [dipu-bd/lightnovel-crawler#720]
Everytime I download from this link I get this error

error: 'data-echo'

- Novel URL: [https://9kqw.com/book/index?id=41503]
- App Version: [2.24.1]
- Package: [Pip]
- OS: [Windows 10]

**Comment by dipu-bd** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 4, in <module>
    main()
  File "./lncrawl/__init__.py", line 13, in main
    start_app()
  File "./lncrawl/core/__init__.py", line 76, in start_app
    raise err
  File "./lncrawl/core/__init__.py", line 73, in start_app
    run_bot(bot)
  File "./lncrawl/bots/__init__.py", line 17, in run_bot
    ConsoleBot().start()
  File "./lncrawl/bots/console/start.py", line 58, in start
    self.app.get_novel_info()
  File "./lncrawl/core/app.py", line 130, in get_novel_info
    self.crawler.read_novel_info()
  File "./lncrawl/sources/9kqw.py", line 43, in read_novel_info
    soup.select_one('#content .detail-thumb-box img')['data-echo'])
  File "/home/dipu/projects/sai-tools/venv/lib/python3.8/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'data-echo'
```

**Comment by dipu-bd** [comment]
looks like they changed the class names. we need to fix the crawler
