### ISSUE TITLE
[WinError 10060] wuxiaworld.com

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#759]
Getting stuck on downloading chapters, just sits there for a while the gives errors.

```
? Enter novel page url or query novel: https://www.wuxiaworld.com/novel/overgeared
Retrieving novel info...
https://www.wuxiaworld.com/novel/overgeared
NOVEL: Overgeared
28 volumes and 1377 chapters found
? Enter output directory: C:\Users\User\Downloads\Lightnovels\www-wuxiaworld-com\Overgeared
? What to do with existing folder?  Remove old folder and start fresh
? Which chapters to download?  Everything! (1377 chapters)
? 1377 chapters selected  Continue
? How many files to generate?  Pack everything into a single file
Downloading chapters |                                | 0/1377Failed to download chapter body
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x06DA4340>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4340>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4340>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Failed to download chapter body
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x06DA4BC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4BC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4BC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Failed to download chapter body
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x06DA4A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06DA4A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-2
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-3
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-1
Downloading chapters |                                | 3/1377Failed to download chapter body
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x05DF8FD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8FD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8FD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x05DF8D48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8D48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8D48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-4
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-5
Downloading chapters |                                | 5/1377Failed to download chapter body
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x05DF8EE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8EE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\lncrawl\core\downloader.py", line 124, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "c:\python38\lib\site-packages\lncrawl\sources\wuxiacom.py", line 123, in download_chapter_body
    soup = self.get_soup(chapter['url'])
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 200, in get_soup
    response = self.get_response(*args, **kwargs)
  File "c:\python38\lib\site-packages\lncrawl\utils\crawler.py", line 167, in get_response
    response = self.scraper.get(url, **kargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wuxiaworld.comnovel', port=443): Max retries exceeded with url: /overgeared/og-chapter-6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05DF8EE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Body is empty: https://www.wuxiaworld.comnovel/overgeared/og-chapter-6
Downloading chapters |                                | 6/1377
```

**Let us know**
- Novel URL: https://www.wuxiaworld.com/novel/overgeared
- App Version: 2.24.3
- Package: pip
- OS: Windows 10 (Latest)

**Comment by Galunid** [comment]
#757 should fix that

**Comment by SirGryphin** [comment]
@Galunid 

Thanks, changed it on my dev version and seems to be working fine now.
