### ISSUE TITLE
[novelringan] AttributeError: 'NoneType' object has no attribute 'extract'

### ISSUE THREAD

**Issue by AncientCatz** [dipu-bd/lightnovel-crawler#909]
**Describe the bug**

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/lncrawl/core/downloader.py", line 122, in download_chapter_body
    body = app.crawler.download_chapter_body(chapter)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/lncrawl/sources/novelringan.py", line 52, in download_chapter_body
    soup.select_one('#bacotan').extract
AttributeError: 'NoneType' object has no attribute 'extract'
Body is empty: https://novelringan.com/tomb-raider-king-chapter-1/`

**Let us know**
- Novel URL: https://novelringan.com/series/tomb-raider-king/
- App Version: 2.26.0
- Package: pip
- OS: TermuxOS Android 10

**Comment by SirGryphin** [comment]
Fixed and added to #929
